server:
  port: 9001

spring:
    application:
         name: API-GETWAY

 
 ##GATEWAY CONFIGURATIONS
 
# spring:
#cloud:
#  gateway:
#    routes:
#    - id: customer-service
#      uri: lb://customer-service
#      predicates:
#      - Path=/customer/**
#    - id: product-service
#      uri: lb//product-service
#      predicates:
#      - Path=/product/**

    
      
#cloud:
#  gateway:
#    routes:
#     - id: USER-SERVICE
#       url: lb://USER-SERVICE
#       predicate: 
#        - path=/product/**
        
eureka:
  instance:
    prefer-ip-address: true
    client:
     fetch-register: true
     register-with-eureka: true
     service-url:
     defaultZone: http://localhost:8761/eureka/      
    


#spring:
#  application:
#    name: api-gateway

#cloud:
#    config:
#      fail-fast: false
#      discovery.enabled: false
#      uri: http://configserver:8888
#
#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl.defaultZone: http://eurekaserver:8761/eureka

//spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
        - id: product-service
          uri: lb://product-service
          predicates:
             - Path=/product/**
       ##RestApi configuration
        - id: restApi
          uri: lb://restApi
          predicates:
             - Path=/rest/** 
# eureka:
#  client:
#     eureka.client.register-with-eureka: true
#     eureka.client.fetch-registry: true
##    register-with-eureka: true
##    fetch-registry: true
#  service-url:
#      defaultZone: http://localhost:8761/erureka/
#      instance:
#      hostname: localhost